### ISSUE TITLE
Update eslint peer dependency version

### ISSUE THREAD

**Issue by jenskuhrjorgensen** [mportuga/eslint-detailed-reporter#28]
Hi

First of: Thanks for the library! 👍 

On `npm list` I'm getting an error about missing peer dependency, because I use a higher version of `eslint` than  what is currently required in by `eslint-detailed-reporter` in `package.json`: `3.0.0 - 5.9999.9999`.

So far I've not identified any bugs with this library and `eslint` version ^7, so I think you should update to either:
`"eslint": "*"`
To allow all versions of `eslint`, or
`"eslint": ">= 3.0.0 < 8"`
To allow all versions of `eslint` between 3 (included) and 8 (not included). This would require continuous updates whenever you want to support new versions of `eslint`. 

Let me know what you think. 

Best regards
Jens

**Comment by nifr** [comment]
I've tested the formatter with recent `esliint` version `8.1.0` and it works flawlessly.

@mportuga Would it be possible to update the `peerDependencies` to include something like `"eslint": ">= 3.0.0 < 8.2"`.

It's very unlikely the formatter will break - even with upcoming eslint `8.x` versions - so even a more permissive constraint `"eslint": ">=3.0.0 <9"` should be fine.

We really like the detailed report but the `npm` / `yarn` warnings are somewhat annying.

Can I do anything to help resolve this peer dependency mismatch and get a new version out some time soon? 

Thanks for open-sourcing the formatter and have a great day :)
