### ISSUE TITLE
List ignored rules

### ISSUE THREAD

**Issue by hitmands** [mportuga/eslint-detailed-reporter#6]
Usually happens that we need to **ignore** some specific eslint warnings/errors:

```javascript
const thing = new Thing(); // eslint-disable-line no-use-before-define

function Thing() {}
```
of course, this was just an example.

would be reasonable to include a report of `what`, `how many` and `where` rules are ignored?

**Comment by mportuga** [comment]
I am not sure. For the most part, I can only work with what ESLint gives me, and I don't think it returns that information, so I don't know if I can report it. I will look into it and see if it is possible via ESLint itself. If not, I might just try to see if I can add some extra logic based on the logic that I already have in place for printing the JS files.
