### ISSUE TITLE
eslint support 4.x

### ISSUE THREAD

**Issue by sarkiroka** [mportuga/eslint-detailed-reporter#7]
We use this amazing report tool, but the npm writes
`npm WARN eslint-detailed-reporter@0.7.2 requires a peer of eslint@3.x but none is installed. You must install peer dependencies yourself.`
We don't want to step back with eslint to 3.x, and npm doesn't allow install both of 3.x and 4.x

**Comment by mportuga** [comment]
Fixed in 0.7.3
